// /*
//  * Copyright (c) 2024 NS-3 Security Extension Project
//  *
//  * Author: Oded Ofek <odedofek2@gmail.com>
//  */

// #include "olsr-defense-full-coverage.h"
// #include "ns3/log.h"
// #include "ns3/simulator.h"
// #include <iostream>
// #include <iomanip>

// namespace ns3 {
// namespace olsr {

// NS_LOG_COMPONENT_DEFINE("OlsrDefenseFullCoverage");

// NS_OBJECT_ENSURE_REGISTERED(OlsrDefenseFullCoverage);

// TypeId
// OlsrDefenseFullCoverage::GetTypeId(void)
// {
//   static TypeId tid = TypeId("ns3::olsr::OlsrDefenseFullCoverage")
//     .SetParent<OlsrDefenseStrategy>()
//     .SetGroupName("Olsr")
//     .AddConstructor<OlsrDefenseFullCoverage>();
//   return tid;
// }

// OlsrDefenseFullCoverage::OlsrDefenseFullCoverage()
//   : m_protocol(nullptr),
//     m_cntSetup(0), m_cntPeriodic(0), m_cntIsMalicious(0),
//     m_cntRecvHello(0), m_cntRecvTc(0), m_cntTcGen(0),
//     m_cntDataRecv(0), m_cntDataFwd(0), m_cntDataDrop(0),
//     m_cntPromisc(0)
// {
// }

// OlsrDefenseFullCoverage::~OlsrDefenseFullCoverage()
// {
// }

// // ==================== Lifecycle ====================

// void 
// OlsrDefenseFullCoverage::Setup(RoutingProtocol* proto, Ipv4Address nodeAddress)
// {
//     m_protocol = proto;
//     m_myAddress = nodeAddress;
//     m_cntSetup++;
    
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: Setup on Node " << m_myAddress << std::endl;
// }

// void 
// OlsrDefenseFullCoverage::PeriodicCheck()
// {
//     m_cntPeriodic++;
    
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: PeriodicCheck on Node " << m_myAddress << "\n"
//               << "    --- STATS REPORT ---\n"
//               << "    Setup:       " << m_cntSetup << "\n"
//               << "    IsMalicious: " << m_cntIsMalicious << "\n"
//               << "    RecvHello:   " << m_cntRecvHello << "\n"
//               << "    RecvTc:      " << m_cntRecvTc << "\n"
//               << "    TcGenerated: " << m_cntTcGen << "\n"
//               << "    DataRecv:    " << m_cntDataRecv << "\n"
//               << "    DataFwd:     " << m_cntDataFwd << "\n"
//               << "    DataDrop:    " << m_cntDataDrop << "\n"
//               << "    PromiscMon:  " << m_cntPromisc << "\n"
//               << "    --------------------" << std::endl;
// }

// // ==================== Security Logic ====================

// bool 
// OlsrDefenseFullCoverage::IsMalicious(Ipv4Address addr)
// {
//     m_cntIsMalicious++;
//     // We log rarely to avoid spamming, but enough to verify it works
//     if (m_cntIsMalicious % 50 == 0 || m_cntIsMalicious < 5) 
//     {
//         std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//                   << "HOOK_TRIGGERED: IsMalicious checked for " << addr << std::endl;
//     }
//     return false; // Benign behavior for QA
// }

// std::set<Ipv4Address> 
// OlsrDefenseFullCoverage::GetBlacklist() const
// {
//     return {};
// }

// // ==================== Control Plane ====================

// void 
// OlsrDefenseFullCoverage::OnRecvHello(Ipv4Address senderAddress,
//                                      Ptr<const Packet> packet, 
//                                      const MessageHeader& msg, 
//                                      const MessageHeader::Hello& hello)
// {
//     m_cntRecvHello++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnRecvHello from " << senderAddress 
//               << ", Willingness=" << (int)hello.willingness << std::endl;
// }

// void 
// OlsrDefenseFullCoverage::OnRecvTc(Ipv4Address senderIfaceAddr, 
//                                   Ptr<const Packet> packet, 
//                                   const MessageHeader& msg, 
//                                   const MessageHeader::Tc& tc)
// {
//     m_cntRecvTc++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnRecvTc from " << senderIfaceAddr 
//               << ", Origin=" << msg.GetOriginatorAddress() 
//               << ", ANSN=" << tc.ansn << std::endl;
// }

// void 
// OlsrDefenseFullCoverage::OnTcGenerated(const MessageHeader::Tc& tc)
// {
//     m_cntTcGen++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnTcGenerated by Me (" << m_myAddress << ")"
//               << ", ANSN=" << tc.ansn 
//               << ", Advertised Neighbors=" << tc.neighborAddresses.size() << std::endl;
// }

// // ==================== Data Plane ====================

// void 
// OlsrDefenseFullCoverage::OnDataPacketReceived(Ptr<const Packet> packet,
//                                               Ipv4Address source,
//                                               Ipv4Address destination,
//                                               Ipv4Address nextHop)
// {
//     m_cntDataRecv++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnDataPacketReceived. Src=" << source 
//               << " Dst=" << destination << " NextHop=" << nextHop 
//               << " Size=" << packet->GetSize() << std::endl;
// }

// void 
// OlsrDefenseFullCoverage::OnDataPacketForwarded(Ptr<const Packet> packet, 
//                                                Ipv4Address nextHop,
//                                                Ipv4Address finalDest)
// {
//     m_cntDataFwd++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnDataPacketForwarded. To NextHop=" << nextHop 
//               << " For FinalDst=" << finalDest << std::endl;
// }

// void 
// OlsrDefenseFullCoverage::OnDataPacketDropped(Ptr<const Packet> packet, 
//                                              Ipv4Address destination,
//                                              uint8_t reason)
// {
//     m_cntDataDrop++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnDataPacketDropped. Dest=" << destination 
//               << " Reason Code=" << (int)reason << std::endl;
// }

// // ==================== Promiscuous / Monitoring ====================

// void 
// OlsrDefenseFullCoverage::OnNeighborForwardedPacket(Ipv4Address neighbor,
//                                                    Ptr<const Packet> packet)
// {
//     m_cntPromisc++;
//     std::cout << "[QA-COVERAGE] [" << Simulator::Now().GetSeconds() << "s] "
//               << "HOOK_TRIGGERED: OnNeighborForwardedPacket. "
//               << "Observed Neighbor=" << neighbor 
//               << " Forwarding Pkt Size=" << packet->GetSize() << std::endl;
// }

// } // namespace olsr
// } // namespace ns3